# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interfaces.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10interfaces.proto\"\xeb\x01\n\tInterface\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x10\n\x08\x61\x64min_up\x18\x03 \x01(\x08\x12\x0f\n\x07oper_up\x18\x04 \x01(\x08\x12\x0b\n\x03mtu\x18\x05 \x01(\r\x12\x13\n\x0bmac_address\x18\x06 \x01(\t\x12\x14\n\x0cipv4_address\x18\x07 \x01(\t\x12\x12\n\nspeed_mbps\x18\x08 \x01(\x04\x12\x11\n\tin_octets\x18\t \x01(\x04\x12\x12\n\nout_octets\x18\n \x01(\x04\x12\x11\n\tin_errors\x18\x0b \x01(\x04\x12\x12\n\nout_errors\x18\x0c \x01(\x04\"5\n\x13InterfaceCollection\x12\x1e\n\ninterfaces\x18\x01 \x03(\x0b\x32\n.Interfaceb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'interfaces_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INTERFACE._serialized_start=21
  _INTERFACE._serialized_end=256
  _INTERFACECOLLECTION._serialized_start=258
  _INTERFACECOLLECTION._serialized_end=311
# @@protoc_insertion_point(module_scope)
